// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions defaultOptions = android;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbqZzaxUEvYg-DaE34NOaYUNeqmBP8ISQ',
    appId: '1:767492699676:web:e98fc83e0109b5778051d9',
    messagingSenderId: '767492699676',
    projectId: 'budgeto-0',
    authDomain: 'budgeto-0.firebaseapp.com',
    storageBucket: 'budgeto-0.firebasestorage.app',
    measurementId: 'G-G048DE6SHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkQupqqm5msbimn_OtejAMtc41UoDFOKQ',
    appId: '1:767492699676:android:e41b8dde0f4b69468051d9',
    messagingSenderId: '767492699676',
    projectId: 'budgeto-0',
    storageBucket: 'budgeto-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBG2Uccp-rSeW0cLQ58ye24MlHiooeRX0',
    appId: '1:767492699676:ios:967460803244f2408051d9',
    messagingSenderId: '767492699676',
    projectId: 'budgeto-0',
    storageBucket: 'budgeto-0.firebasestorage.app',
    iosBundleId: 'com.example.budgeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBG2Uccp-rSeW0cLQ58ye24MlHiooeRX0',
    appId: '1:767492699676:ios:967460803244f2408051d9',
    messagingSenderId: '767492699676',
    projectId: 'budgeto-0',
    storageBucket: 'budgeto-0.firebasestorage.app',
    iosBundleId: 'com.example.budgeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbqZzaxUEvYg-DaE34NOaYUNeqmBP8ISQ',
    appId: '1:767492699676:web:e3ad9a3f037cdc838051d9',
    messagingSenderId: '767492699676',
    projectId: 'budgeto-0',
    authDomain: 'budgeto-0.firebaseapp.com',
    storageBucket: 'budgeto-0.firebasestorage.app',
    measurementId: 'G-LCP2FMX446',
  );
}
